# Generated by Django 4.1.4 on 2022-12-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Pupil name....', max_length=400)),
                ('date', models.DateField(blank=True, help_text='Date | Month | Year', null=True)),
                ('email_address', models.CharField(help_text='Enter email address ...', max_length=200, null=True)),
                ('phone_number', models.IntegerField()),
                ('passport_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payment', models.BooleanField(help_text='if paid, click the button')),
                ('one_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
